name: build

on: [push, pull_request]

env:
  BUILD_TYPE: Debug

jobs:
  linux:
    timeout-minutes: 10
    
    strategy:
      matrix:
        compiler: [g++, clang++]
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment      
      shell: bash

      run: mkdir build
      
    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      env:
        CXX: ${{ matrix.compiler }}

      run: |
        cmake -DECS_BUILD_TESTING=ON ..
        make

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash

      run: ctest -C $BUILD_TYPE

  windows:
    timeout-minutes: 10
    
    strategy:
      matrix:
        os: [windows-latest, windows-2016]
        toolset: [clang-cl, default]
        include:
          - toolset: clang-cl
            toolset_option: -T"ClangCl"
        exclude:
          - os: windows-2016
            toolset: clang-cl
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment      
      shell: bash

      run: mkdir build
      
    - name: Build

      shell: bash
      working-directory: ${{github.workspace}}/build

      run: |
        cmake -DECS_BUILD_TESTING=ON ${{ matrix.toolset_option }} ..
        cmake --build .

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      env:
        CTEST_OUTPUT_ON_FAILURE: 1

      run: ctest -C $BUILD_TYPE
  macos:
    timeout-minutes: 10
    
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment      

      run: mkdir build
      
    - name: Build

      working-directory: ${{github.workspace}}/build

      run: |
        cmake -DECS_BUILD_TESTING=ON ..
        make

    - name: Test
      working-directory: ${{github.workspace}}/build
      env:
        CTEST_OUTPUT_ON_FAILURE: 1

      run: ctest -C $BUILD_TYPE
